"""
This type stub file was generated by pyright.
"""

from .c4a_compile import C4ACompiler, compile, compile_file, validate
from .c4a_result import CompilationResult, ErrorDetail, ErrorType, Severity, Suggestion, ValidationResult, WarningDetail

"""
C4A-Script: A domain-specific language for web automation in Crawl4AI
"""
__all__ = ["C4ACompiler", "compile", "validate", "compile_file", "CompilationResult", "ValidationResult", "ErrorDetail", "WarningDetail", "ErrorType", "Severity", "Suggestion"]
