"""
This type stub file was generated by pyright.
"""

import warnings
from .async_webcrawler import AsyncWebCrawler, CacheMode
from .async_configs import BrowserConfig, CrawlerRunConfig, GeolocationConfig, HTTPCrawlerConfig, LLMConfig, LinkPreviewConfig, MatchMode, ProxyConfig, SeedingConfig, VirtualScrollConfig
from .content_scraping_strategy import ContentScrapingStrategy, LXMLWebScrapingStrategy, WebScrapingStrategy
from .async_logger import AsyncLogger, AsyncLoggerBase
from .proxy_strategy import ProxyRotationStrategy, RoundRobinProxyStrategy
from .extraction_strategy import CosineStrategy, ExtractionStrategy, JsonCssExtractionStrategy, JsonLxmlExtractionStrategy, JsonXPathExtractionStrategy, LLMExtractionStrategy, RegexExtractionStrategy
from .chunking_strategy import ChunkingStrategy, RegexChunking
from .markdown_generation_strategy import DefaultMarkdownGenerator
from .table_extraction import DefaultTableExtraction, LLMTableExtraction, NoTableExtraction, TableExtractionStrategy
from .content_filter_strategy import BM25ContentFilter, LLMContentFilter, PruningContentFilter, RelevantContentFilter
from .models import CrawlResult, DisplayMode, MarkdownGenerationResult
from .components.crawler_monitor import CrawlerMonitor
from .link_preview import LinkPreview
from .async_dispatcher import BaseDispatcher, MemoryAdaptiveDispatcher, RateLimiter, SemaphoreDispatcher
from .docker_client import Crawl4aiDockerClient
from .hub import CrawlerHub
from .browser_profiler import BrowserProfiler
from .deep_crawling import BFSDeepCrawlStrategy, BestFirstCrawlingStrategy, CompositeScorer, ContentTypeFilter, DFSDeepCrawlStrategy, DeepCrawlDecorator, DeepCrawlStrategy, DomainAuthorityScorer, DomainFilter, FilterChain, FilterStats, FreshnessScorer, KeywordRelevanceScorer, PathDepthScorer, SEOFilter, URLFilter, URLPatternFilter, URLScorer
from .async_url_seeder import AsyncUrlSeeder
from .adaptive_crawler import AdaptiveConfig, AdaptiveCrawler, CrawlState, CrawlStrategy, StatisticalStrategy
from .script import CompilationResult, ErrorDetail, ValidationResult, compile as c4a_compile, compile_file as c4a_compile_file, validate as c4a_validate
from .browser_adapter import BrowserAdapter, PlaywrightAdapter, UndetectedAdapter
from .utils import hooks_to_string, setup_colab_environment, start_colab_display_server

__all__ = ["AsyncLoggerBase", "AsyncLogger", "AsyncWebCrawler", "BrowserProfiler", "LLMConfig", "GeolocationConfig", "SeedingConfig", "VirtualScrollConfig", "AsyncUrlSeeder", "AdaptiveCrawler", "AdaptiveConfig", "CrawlState", "CrawlStrategy", "StatisticalStrategy", "DeepCrawlStrategy", "BFSDeepCrawlStrategy", "BestFirstCrawlingStrategy", "DFSDeepCrawlStrategy", "FilterChain", "URLPatternFilter", "ContentTypeFilter", "DomainFilter", "FilterStats", "URLFilter", "SEOFilter", "KeywordRelevanceScorer", "URLScorer", "CompositeScorer", "DomainAuthorityScorer", "FreshnessScorer", "PathDepthScorer", "DeepCrawlDecorator", "CrawlResult", "CrawlerHub", "CacheMode", "MatchMode", "ContentScrapingStrategy", "WebScrapingStrategy", "LXMLWebScrapingStrategy", "BrowserConfig", "CrawlerRunConfig", "HTTPCrawlerConfig", "ExtractionStrategy", "LLMExtractionStrategy", "CosineStrategy", "JsonCssExtractionStrategy", "JsonXPathExtractionStrategy", "JsonLxmlExtractionStrategy", "RegexExtractionStrategy", "ChunkingStrategy", "RegexChunking", "DefaultMarkdownGenerator", "TableExtractionStrategy", "DefaultTableExtraction", "NoTableExtraction", "RelevantContentFilter", "PruningContentFilter", "BM25ContentFilter", "LLMContentFilter", "BaseDispatcher", "MemoryAdaptiveDispatcher", "SemaphoreDispatcher", "RateLimiter", "CrawlerMonitor", "LinkPreview", "DisplayMode", "MarkdownGenerationResult", "Crawl4aiDockerClient", "ProxyRotationStrategy", "RoundRobinProxyStrategy", "ProxyConfig", "start_colab_display_server", "setup_colab_environment", "hooks_to_string", "c4a_compile", "c4a_validate", "c4a_compile_file", "CompilationResult", "ValidationResult", "ErrorDetail", "BrowserAdapter", "PlaywrightAdapter", "UndetectedAdapter", "LinkPreviewConfig"]
