"""
This type stub file was generated by pyright.
"""

logger = ...
def setup_home_directory(): # -> None:
    """Set up the .crawl4ai folder structure in the user's home directory."""
    ...

def post_install(): # -> None:
    """
    Run all post-installation tasks.
    Checks CRAWL4AI_MODE environment variable. If set to 'api',
    skips Playwright browser installation.
    """
    ...

def setup_builtin_browser(): # -> None:
    """Set up a builtin browser for use with Crawl4AI"""
    ...

def install_playwright(): # -> None:
    ...

def run_migration(): # -> None:
    """Initialize database during installation"""
    ...

async def run_doctor(): # -> bool:
    """Test if Crawl4AI is working properly"""
    ...

def doctor():
    """Entry point for the doctor command"""
    ...

