"""
This type stub file was generated by pyright.
"""

from typing import Optional

logger = ...
class DatabaseMigration:
    def __init__(self, db_path: str) -> None:
        ...
    
    async def migrate_database(self): # -> None:
        """Migrate existing database to file-based storage"""
        ...
    


async def backup_database(db_path: str) -> str:
    """Create backup of existing database"""
    ...

async def run_migration(db_path: Optional[str] = ...): # -> None:
    """Run database migration"""
    ...

def main(): # -> None:
    """CLI entry point for migration"""
    ...

if __name__ == "__main__":
    ...
