"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional
from lxml import etree
from .types import LLMConfig

"""
Table extraction strategies for Crawl4AI.

This module provides various strategies for detecting and extracting tables from HTML content.
The strategy pattern allows for flexible table extraction methods while maintaining a consistent interface.
"""
class TableExtractionStrategy(ABC):
    """
    Abstract base class for all table extraction strategies.
    
    This class defines the interface that all table extraction strategies must implement.
    It provides a consistent way to detect and extract tables from HTML content.
    """
    def __init__(self, **kwargs) -> None:
        """
        Initialize the table extraction strategy.
        
        Args:
            **kwargs: Additional keyword arguments for specific strategies
        """
        ...
    
    @abstractmethod
    def extract_tables(self, element: etree.Element, **kwargs) -> List[Dict[str, Any]]:
        """
        Extract tables from the given HTML element.
        
        Args:
            element: The HTML element (typically the body or a container element)
            **kwargs: Additional parameters for extraction
            
        Returns:
            List of dictionaries containing table data, each with:
                - headers: List of column headers
                - rows: List of row data (each row is a list)
                - caption: Table caption if present
                - summary: Table summary attribute if present
                - metadata: Additional metadata about the table
        """
        ...
    


class DefaultTableExtraction(TableExtractionStrategy):
    """
    Default table extraction strategy that implements the current Crawl4AI table extraction logic.
    
    This strategy uses a scoring system to identify data tables (vs layout tables) and
    extracts structured data including headers, rows, captions, and summaries.
    It handles colspan and rowspan attributes to preserve table structure.
    """
    def __init__(self, **kwargs) -> None:
        """
        Initialize the default table extraction strategy.
        
        Args:
            table_score_threshold (int): Minimum score for a table to be considered a data table (default: 7)
            min_rows (int): Minimum number of rows for a valid table (default: 0)
            min_cols (int): Minimum number of columns for a valid table (default: 0)
            **kwargs: Additional parameters passed to parent class
        """
        ...
    
    def extract_tables(self, element: etree.Element, **kwargs) -> List[Dict[str, Any]]:
        """
        Extract all data tables from the HTML element.
        
        Args:
            element: The HTML element to search for tables
            **kwargs: Additional parameters (can override instance settings)
            
        Returns:
            List of dictionaries containing extracted table data
        """
        ...
    
    def is_data_table(self, table: etree.Element, **kwargs) -> bool:
        """
        Determine if a table is a data table (vs. layout table) using a scoring system.
        
        Args:
            table: The table element to evaluate
            **kwargs: Additional parameters (e.g., table_score_threshold)
            
        Returns:
            True if the table scores above the threshold, False otherwise
        """
        ...
    
    def extract_table_data(self, table: etree.Element) -> Dict[str, Any]:
        """
        Extract structured data from a table element.
        
        Args:
            table: The table element to extract data from
            
        Returns:
            Dictionary containing:
                - headers: List of column headers
                - rows: List of row data (each row is a list)
                - caption: Table caption if present
                - summary: Table summary attribute if present
                - metadata: Additional metadata about the table
        """
        ...
    


class NoTableExtraction(TableExtractionStrategy):
    """
    A strategy that does not extract any tables.
    
    This can be used to explicitly disable table extraction when needed.
    """
    def extract_tables(self, element: etree.Element, **kwargs) -> List[Dict[str, Any]]:
        """
        Return an empty list (no tables extracted).
        
        Args:
            element: The HTML element (ignored)
            **kwargs: Additional parameters (ignored)
            
        Returns:
            Empty list
        """
        ...
    


class LLMTableExtraction(TableExtractionStrategy):
    """
    LLM-based table extraction strategy that uses language models to intelligently extract 
    and structure table data, handling complex cases like rowspan, colspan, and nested tables.
    
    This strategy uses an LLM to understand table structure semantically and convert it to 
    structured data that can be easily consumed by pandas DataFrames.
    """
    TABLE_EXTRACTION_PROMPT = ...
    def __init__(self, llm_config: Optional[LLMConfig] = ..., css_selector: Optional[str] = ..., max_tries: int = ..., enable_chunking: bool = ..., chunk_token_threshold: int = ..., min_rows_per_chunk: int = ..., max_parallel_chunks: int = ..., verbose: bool = ..., **kwargs) -> None:
        """
        Initialize the LLM-based table extraction strategy.
        
        Args:
            llm_config: LLM configuration for the extraction
            css_selector: Optional CSS selector to focus on specific page areas
            max_tries: Maximum number of retries if LLM fails to extract tables (default: 3)
            enable_chunking: Enable smart chunking for large tables (default: True)
            chunk_token_threshold: Token threshold for triggering chunking (default: 3000)
            min_rows_per_chunk: Minimum rows per chunk (default: 10)
            max_parallel_chunks: Maximum parallel chunk processing (default: 5)
            verbose: Enable verbose logging
            **kwargs: Additional parameters passed to parent class
        """
        ...
    
    def extract_tables(self, element: etree.Element, **kwargs) -> List[Dict[str, Any]]:
        """
        Extract tables from HTML using LLM.
        
        Args:
            element: The HTML element to search for tables
            **kwargs: Additional parameters
            
        Returns:
            List of dictionaries containing extracted table data
        """
        ...
    


