"""
This type stub file was generated by pyright.
"""

from typing import Dict, Optional

class AnchorElement:
    __slots__ = ...
    def __init__(self, attrs: Dict[str, Optional[str]], count: int, outcount: int) -> None:
        ...
    


class ListElement:
    __slots__ = ...
    def __init__(self, name: str, num: int) -> None:
        ...
    


